#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(readFileSync(join(root, 'standards/registry.json'), 'utf8'));
const compositions = JSON.parse(readFileSync(join(root, 'standards/compositions.json'), 'utf8'));
const references = JSON.parse(readFileSync(join(root, 'standards/references.json'), 'utf8'));
const checkOnly = process.argv.includes('--check');
const generatedBy = '<!-- Generated by standards/generate-catalog.mjs; edit standards/*.json instead. -->';

const registryById = new Map(registry.standards.map((standard) => [standard.id, standard]));
const titleWords = new Map([
  ['api', 'API'],
  ['cf', 'CF'],
  ['ci', 'CI'],
  ['cli', 'CLI'],
  ['d1', 'D1'],
  ['github', 'GitHub'],
  ['kb', 'KB'],
  ['mcp', 'MCP'],
  ['openapi', 'OpenAPI'],
  ['saas', 'SaaS'],
  ['sdk', 'SDK'],
  ['spa', 'SPA'],
  ['typescript', 'TypeScript'],
  ['vscode', 'VS Code']
]);

const titleize = (id) => id.split('-').map((part) => titleWords.get(part) ?? part.charAt(0).toUpperCase() + part.slice(1)).join(' ');

const itemById = new Map(compositions.stackItems.map((item) => [item.id, item]));

// Display names come from metadata, never from a heuristic: registry.json owns standard
// titles, compositions.json owns stack item titles. titleize() survives only as a fallback
// for grouping keys such as stack item kinds, which have no metadata entry of their own.
const standardTitle = (id) => registryById.get(id)?.title ?? titleize(id);
const itemTitle = (id) => itemById.get(id)?.title ?? titleize(id);
const entityTitle = (id) => registryById.get(id)?.title ?? itemById.get(id)?.title ?? titleize(id);

const mdLink = (label, href) => `[${label}](${href})`;
const htmlLink = (label, href, cls = '') => `<a href="${escapeHtml(href)}"${cls ? ` class="${cls}"` : ''}>${escapeHtml(label)}</a>`;

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function normalizeStandardUrl(url) {
  return url ? url.replace(/^https:\/\/vibecodeqa\.online/, '') : null;
}

function relativeDocsUrl(url, fromDir) {
  if (!url) return null;
  const clean = url.replace(/^https:\/\/vibecodeqa\.online/, '').replace(/^\/docs\/standards\//, '');
  const noSlash = clean.replace(/\/$/, '');
  if (!noSlash) return 'index.md';
  const target = join(root, 'docs/docs/standards', `${noSlash}.md`);
  const source = join(root, 'docs/docs/standards', fromDir);
  return relative(source, target).replaceAll('\\', '/');
}

function editionLabel(standard) {
  const latest = standard.editions?.find((edition) => edition.status === 'latest');
  return latest?.version ?? null;
}

function isComposedAuthored(composed) {
  return composed.status === 'authored' && normalizeStandardUrl(composed.standardUrl);
}

function isAliasOnly(composed) {
  const standardUrl = normalizeStandardUrl(composed.standardUrl);
  return Boolean(standardUrl && !standardUrl.includes(`/standards/${composed.id}/`));
}

function isStackStandard(composed) {
  return Boolean(composed.docsUrl?.includes('/stacks/') && !isAliasOnly(composed));
}

function plannedStandards() {
  const composedIds = new Set(compositions.composedStandards.map((standard) => standard.id));
  const compositionPlanned = compositions.composedStandards.filter((standard) => standard.status === 'planned');
  const registryOnly = registry.standards
    .filter((standard) => standard.status === 'planned' && !composedIds.has(standard.id))
    .filter((standard) => standard.docsUrl || standard.type === 'cross-cutting')
    .map((standard) => ({
      id: standard.id,
      status: 'planned',
      aliases: standard.aliases ?? [],
      stackItems: standard.composes ?? [],
      ownedRules: [standard.summary],
      benefits: [],
      docsUrl: standard.docsUrl,
      standardUrl: null,
      latestEdition: null
    }));
  return [...compositionPlanned, ...registryOnly];
}

function writeIfChanged(path, next) {
  const abs = join(root, path);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : '';
  if (current === next) return false;
  if (checkOnly) {
    console.error(`${path} is stale; run node standards/generate-catalog.mjs`);
    return true;
  }
  writeFileSync(abs, next);
  return true;
}

function writeJsonIfChanged(path, value) {
  return writeIfChanged(path, `${JSON.stringify(value, null, 2)}\n`);
}

function replaceGeneratedBlock(path, blockName, body) {
  const abs = join(root, path);
  const current = readFileSync(abs, 'utf8');
  const start = `<!-- BEGIN GENERATED:${blockName} -->`;
  const end = `<!-- END GENERATED:${blockName} -->`;
  const pattern = new RegExp(`${escapeRegex(start)}[\\s\\S]*?${escapeRegex(end)}`);
  if (!pattern.test(current)) {
    throw new Error(`${path}: missing generated block ${blockName}`);
  }
  const next = current.replace(pattern, `${start}\n${generatedBy}\n${body.trim()}\n${end}`);
  return writeIfChanged(path, next);
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// TOML has no comment syntax we can reuse from Markdown, so nav blocks are fenced with
// `# BEGIN GENERATED:<name>` / `# END GENERATED:<name>` at the block's own indent level.
function replaceGeneratedTomlBlock(path, blockName, lines, indent) {
  const abs = join(root, path);
  const current = readFileSync(abs, 'utf8');
  const start = `${indent}# BEGIN GENERATED:${blockName}`;
  const end = `${indent}# END GENERATED:${blockName}`;
  const pattern = new RegExp(`${escapeRegex(start)}[\\s\\S]*?${escapeRegex(end)}`);
  if (!pattern.test(current)) {
    throw new Error(`${path}: missing generated block ${blockName}`);
  }
  const body = lines.map((line) => `${indent}${line}`).join('\n');
  const banner = `${indent}# Generated by standards/generate-catalog.mjs; edit standards/*.json instead.`;
  return writeIfChanged(path, current.replace(pattern, `${start}\n${banner}\n${body}\n${end}`));
}

function docsPageSlug(url, section) {
  const normalized = normalizeStandardUrl(url);
  if (!normalized?.startsWith(`/docs/standards/${section}/`)) return null;
  return normalized.replace(`/docs/standards/${section}/`, '').replace(/\/$/, '') || null;
}

// Stack pages in metadata order, aliases included: nav must show every page the catalog
// claims exists, and nothing else.
function navStackPages() {
  const seen = new Set();
  return compositions.composedStandards.flatMap((standard) => {
    const slug = docsPageSlug(standard.docsUrl, 'stacks');
    if (!slug || seen.has(standard.id)) return [];
    seen.add(standard.id);
    return [{ id: standard.id, slug, title: standardTitle(standard.id) }];
  });
}

// Stack items grouped by kind, matching the ordering of the generated items index so the
// sidebar and the index page never disagree about sequence.
function navStackItems() {
  const groups = new Map();
  for (const item of compositions.stackItems) {
    if (!groups.has(item.kind)) groups.set(item.kind, []);
    groups.get(item.kind).push(item);
  }
  return [...groups.values()].flat().flatMap((item) => {
    const slug = docsPageSlug(item.docsUrl, 'items');
    return slug ? [{ id: item.id, slug, title: itemTitle(item.id) }] : [];
  });
}

// Assessment reports are authored files, but which stack pages have one — and in what
// order — is derived from metadata plus on-disk existence.
function navAssessments() {
  const seen = new Set();
  return navStackPages().flatMap((page) => {
    if (seen.has(page.slug)) return [];
    seen.add(page.slug);
    const path = join(root, 'docs/docs/standards/assessments/stacks', `${page.slug}.md`);
    return existsSync(path) ? [page] : [];
  });
}

function navEntry(title, path) {
  return `{ "${title.replaceAll('"', '\\"')}" = "${path}" },`;
}

function generatedNavStackStandards() {
  return [
    navEntry('Index', 'standards/stacks/index.md'),
    ...navStackPages().map((page) => navEntry(page.title, `standards/stacks/${page.slug}.md`))
  ];
}

function generatedNavStackItems() {
  return [
    navEntry('Index', 'standards/items/index.md'),
    ...navStackItems().map((item) => navEntry(item.title, `standards/items/${item.slug}.md`))
  ];
}

function generatedNavAssessments() {
  return [
    navEntry('Index', 'standards/assessments/index.md'),
    ...navAssessments().map((page) => navEntry(page.title, `standards/assessments/stacks/${page.slug}.md`))
  ];
}

function aliasNoteFor(standard) {
  const aliases = compositions.composedStandards.filter((entry) =>
    entry.id !== standard.id &&
    isAliasOnly(entry) &&
    normalizeStandardUrl(entry.standardUrl) === normalizeStandardUrl(standard.standardUrl));
  if (!aliases.length) return '';
  return ` Also cataloged as ${aliases.map((entry) => `\`${entry.id}\``).join(', ')}.`;
}

// The "Supported stacks" docs page repeats the authored-rubric inventory for readers who
// arrive from detection rather than from the standards catalog. Generate it from the same
// metadata so the two inventories cannot disagree.
function generatedStacksPageRubrics() {
  const bullet = (standard) => {
    const registryEntry = registryById.get(standard.id);
    const label = `${standardTitle(standard.id)} ${standard.latestEdition}`;
    return `- ${mdLink(label, normalizeStandardUrl(standard.standardUrl))} - ${registryEntry?.summary ?? standard.ownedRules.join(', ')}${aliasNoteFor(standard)}`;
  };
  const stacks = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const crossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));

  return `
### Authored stack rubrics

${stacks.map(bullet).join('\n')}

### Authored cross-cutting rubrics

${crossCutting.map(bullet).join('\n')}
`;
}

function generatedStandardsCatalog() {
  const authoredStack = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const authoredCrossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));
  const aliases = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isAliasOnly(standard));
  const planned = plannedStandards();

  const stackRows = authoredStack.map((standard) => {
    const registryEntry = registryById.get(standard.id);
    const aliases = standard.aliases.length ? ` \`${standard.aliases.join('`, `')}\`` : '';
    return `| ${standardTitle(standard.id)}${aliases} | ${mdLink('Charter', relativeDocsUrl(standard.docsUrl, '.'))} | ${mdLink(`${standardTitle(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))} | ${registryEntry?.summary ?? standard.ownedRules.join(', ')} |`;
  });

  const crossRows = authoredCrossCutting.map((standard) => {
    const catalog = relativeDocsUrl(standard.docsUrl, '.');
    const label = standardTitle(standard.id);
    return `| ${label} | ${catalog ? mdLink('Catalog page', catalog) : '-'} | ${mdLink(`${label} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))} | ${standard.ownedRules.slice(0, 3).join('; ')} |`;
  });

  // Ranked by maturity, not by metadata order: this table is the landing page for the
  // backlog, and a flat list told readers a demoted note and a near-ready charter were the
  // same kind of thing.
  const plannedRows = planned.slice().sort(byMaturity).map((standard) => {
    const catalog = relativeDocsUrl(standard.docsUrl, '.');
    return `| ${catalog ? mdLink(standardTitle(standard.id), catalog) : standardTitle(standard.id)} | ${maturityState(standard.id).label} | ${standard.stackItems.map((id) => entityTitle(id)).join(', ') || '-'} | ${standard.ownedRules.join('; ')} |`;
  });

  const aliasRows = aliases.map((standard) => {
    const target = mdLink(normalizeStandardUrl(standard.standardUrl), normalizeStandardUrl(standard.standardUrl));
    return `- \`${standard.id}\` resolves to ${target}. Aliases: ${standard.aliases.map((alias) => `\`${alias}\``).join(', ') || 'none'}.`;
  });

  return `
## Authored Stack Rubrics

| Stack standard | Charter | Full rubric | What it judges |
|---|---|---|---|
${stackRows.join('\n')}

## Authored Cross-Cutting Rubrics

| Cross-cutting standard | Catalog page | Full rubric | VCQA-owned surface |
|---|---|---|---|
${crossRows.join('\n')}

## Published Aliases

${aliasRows.join('\n') || '- None.'}

## Planned Standards

Ranked by [maturity state](authoring.md#planned-charter-maturity-states). Only a candidate
rubric is close enough to a versioned standard to review a repository against; a backlog entry
exists so the resolver names the right standard, and nothing more.

| Planned standard | Maturity | Composes | VCQA-owned surface |
|---|---|---|---|
${plannedRows.join('\n')}
`;
}

// --- Reference implementation evidence ------------------------------------------------
//
// A reference repo score is a trust signal, so it is metadata with a provenance trail
// (report, assessed commit, CI run, verification date) rather than a number typed into
// each surface by hand. Every reference inventory below renders from these helpers, and
// validate-registry.mjs fails the build when a hand-written page quotes a different one.

const referenceRepos = compositions.referenceImplementations ?? [];
const reposByStatus = (status) => referenceRepos.filter((repo) => repo.status === status);
const primaryRepoFor = (standardId) =>
  referenceRepos.find((repo) => repo.demonstratesPrimary === standardId && repo.evidence);
// Every repo claimed as this standard's reference, including catalog candidates that have
// not been built. A charter must not go quiet about a reference repo that does not exist.
const claimedRepoFor = (standardId) =>
  referenceRepos.find((repo) => repo.demonstratesPrimary === standardId);

// Charter maturity states, documented in docs/docs/standards/authoring.md. `order` drives
// the ranking on every surface that lists planned charters, so the near-ready ones stop
// sitting next to the ones nobody is working on.
const maturityStates = {
  'authored-rubric': {
    order: 0,
    label: 'Authored rubric',
    means: 'A versioned rubric is published and the authored charter bar applies to this page.'
  },
  'candidate-rubric': {
    order: 1,
    label: 'Candidate rubric',
    means: 'Numbered candidate rules carry severity, required evidence, and an exception policy. A versioned rubric can be cut from this page once its promotion criteria are met.'
  },
  'draft-charter': {
    order: 2,
    label: 'Draft charter',
    means: 'Scope, composition, detection signals, and the VCQA-owned rule surface are recorded, but there are no judgeable candidate rules yet. Useful for planning, not for review.'
  },
  backlog: {
    order: 3,
    label: 'Backlog',
    means: 'The stack shape is recorded so gap reports name the right standard. Nobody is working toward a rubric, and nothing on the page is judgeable.'
  }
};

const maturityOf = (standardId) => registryById.get(standardId)?.maturity ?? 'backlog';
const maturityState = (standardId) => maturityStates[maturityOf(standardId)] ?? maturityStates.backlog;
const byMaturity = (a, b) => maturityState(a.id).order - maturityState(b.id).order;

function scoreLabel(evidence) {
  return evidence.grade ? `${evidence.grade} ${evidence.score}/100` : `${evidence.score}/100`;
}

// Until someone publishes an independent assessment of the repo itself, the score is the
// repo's own claim. Say so everywhere it is displayed.
function verificationLabel(evidence) {
  return evidence.independentAssessmentUrl ? 'independently assessed' : 'self-reported';
}

function commitUrl(repo, sha) {
  return `${repo.url}/commit/${sha}`;
}

function evidenceMarkdown(repo) {
  if (!repo.evidence) return 'No report yet';
  const evidence = repo.evidence;
  const parts = [
    `${mdLink(scoreLabel(evidence), evidence.reportUrl)} (${verificationLabel(evidence)})`,
    `commit ${mdLink(`\`${evidence.assessedCommit.slice(0, 7)}\``, commitUrl(repo, evidence.assessedCommit))} (${evidence.assessedAt})`,
    `CI ${mdLink(evidence.ciConclusion, evidence.ciRunUrl)} (${evidence.ciRunAt})`,
    `verified ${evidence.verifiedAt}`
  ];
  if (evidence.independentAssessmentUrl) {
    parts.splice(3, 0, mdLink('independent assessment', evidence.independentAssessmentUrl));
  }
  return parts.join('; ');
}

function evidenceHtml(repo) {
  if (!repo.evidence) return 'No report yet.';
  const evidence = repo.evidence;
  const parts = [
    `${htmlLink(scoreLabel(evidence), evidence.reportUrl)} (${escapeHtml(verificationLabel(evidence))})`,
    `commit ${htmlLink(evidence.assessedCommit.slice(0, 7), commitUrl(repo, evidence.assessedCommit))} (${escapeHtml(evidence.assessedAt)})`,
    `CI ${htmlLink(evidence.ciConclusion, evidence.ciRunUrl)} (${escapeHtml(evidence.ciRunAt)})`,
    `verified ${escapeHtml(evidence.verifiedAt)}`
  ];
  if (evidence.independentAssessmentUrl) {
    parts.splice(3, 0, htmlLink('independent assessment', evidence.independentAssessmentUrl));
  }
  return `${parts.join('; ')}.`;
}

function referenceNotes() {
  return referenceRepos.filter((repo) => repo.note).map((repo) => `- \`${repo.id}\`: ${repo.note}`);
}

function generatedReferenceRepos() {
  const listed = [...reposByStatus('published'), ...reposByStatus('experimental')];
  const rows = listed.map((repo) => {
    const standards = repo.standards?.length ? repo.standards.map((id) => `\`${id}\``).join(', ') : '-';
    return `| ${mdLink(repo.repo, repo.url)} | ${repo.status} | ${standards} | ${repo.demonstrates} | ${evidenceMarkdown(repo)} |`;
  });
  const next = reposByStatus('candidate').map((repo) => `- \`${repo.id}\`: ${repo.demonstrates}`).join('\n');
  const notes = referenceNotes();

  return `
| Repository | Catalog status | Standards demonstrated | What it demonstrates | Score evidence |
|---|---|---|---|---|
${rows.join('\n')}

Scores marked *self-reported* come from the reference repo's own tracked VCQA report at the
listed commit. They are not independent assessments; treat them as claims with a visible
provenance trail, not as third-party proof.
${notes.length ? `\nStatus notes:\n\n${notes.join('\n')}\n` : ''}
Next template candidates:

${next}
`;
}

// The compositions page repeats the reference inventory in prose form for readers arriving
// from the composition map. It used to be a hand-maintained list and had drifted to three
// of the six published repos, so it is generated from the same metadata.
function generatedCompositionsReferenceRepos() {
  const listed = [...reposByStatus('published'), ...reposByStatus('experimental')];
  const lines = listed.map((repo) => {
    const primary = repo.demonstratesPrimary
      ? `primary standard \`${repo.demonstratesPrimary}\``
      : 'no primary stack standard yet';
    return `- ${mdLink(repo.repo, repo.url)} (${repo.status}, ${primary}): ${repo.demonstrates} Score evidence: ${evidenceMarkdown(repo)}.`;
  });
  return `
${lines.join('\n')}
`;
}

// Charter pages cite "the" reference repo for their stack. That claim, its score, and its
// provenance are generated so a charter page cannot fall behind the catalog.
function generatedStackReferenceEvidence(standardId) {
  const repo = primaryRepoFor(standardId);
  if (!repo) throw new Error(`no primary reference implementation with evidence for ${standardId}`);
  const evidence = repo.evidence;
  const independent = evidence.independentAssessmentUrl
    ? mdLink('Published independent assessment', evidence.independentAssessmentUrl)
    : 'None published yet. The score above is the reference repo\'s own claim, not third-party proof.';
  return `
| Score evidence | Value |
|---|---|
| Repository | ${mdLink(repo.repo, repo.url)} (${repo.status}) |
| VCQA report | ${mdLink(scoreLabel(evidence), evidence.reportUrl)} |
| Verification | ${verificationLabel(evidence)} |
| Assessed commit | ${mdLink(`\`${evidence.assessedCommit.slice(0, 7)}\``, commitUrl(repo, evidence.assessedCommit))} |
| Assessed on | ${evidence.assessedAt} |
| CI run | ${mdLink(evidence.ciConclusion, evidence.ciRunUrl)} (${evidence.ciRunAt}) |
| Independent assessment | ${independent} |
| Catalog entry last verified | ${evidence.verifiedAt} |
`;
}

// Maintenance metadata on an authored charter page (edition, review dates, targets,
// lifecycle) is registry data. Generate it so a charter cannot claim a review date the
// registry has moved on from.
function generatedCharterMaintenance(standardId) {
  const registryEntry = registryById.get(standardId);
  const composed = compositions.composedStandards.find((entry) => entry.id === standardId);
  const latest = registryEntry?.editions?.find((edition) => edition.status === 'latest');
  if (!latest) throw new Error(`no latest edition for ${standardId}`);
  const lifecycle = latest.lifecycle ?? {};
  const targets = Object.entries(latest.targets ?? {})
    .map(([key, value]) => `\`${key} ${value}\``)
    .join(', ') || 'none recorded';
  const rows = [
    ['Latest edition', mdLink(`${standardTitle(standardId)} ${latest.version}`, normalizeStandardUrl(registryEntry.standardUrl))],
    ['Pin reports and scans to', `\`${normalizeStandardUrl(registryEntry.standardUrl)}\``],
    ['Last reviewed', latest.reviewed],
    ['Next review due', latest.nextReview],
    ['Edition targets', targets],
    ['Lifecycle', `${lifecycle.deprecated ? 'deprecated' : 'active'}${lifecycle.supersededBy ? `, superseded by ${lifecycle.supersededBy}` : ''}`],
    ['Errata', lifecycle.errata?.length ? lifecycle.errata.join('; ') : 'none'],
    ['Composes', (composed?.stackItems ?? []).map((id) => `\`${id}\``).join(', ') || 'metadata-only']
  ];
  return `
| Maintenance | Value |
|---|---|
${rows.map(([label, value]) => `| ${label} | ${value} |`).join('\n')}

Editions are cut on material change, not on a calendar. A review that finds the edition
still correct moves **Last reviewed** forward without a new edition. Metadata lives in
[\`standards/registry.json\`](https://github.com/vibecodeqa/vibecodeqa/blob/main/standards/registry.json).
`;
}

// A planned charter's own header used to be one hand-typed line, "Status: Planned charter",
// which said the same thing on a page with twelve governed candidate rules and on a page
// nobody has touched since it was filed. The maturity state, what that state means, whether
// a reference implementation actually exists, and what blocks promotion are registry data,
// so they are generated onto the page instead.
function generatedCharterStatus(standardId) {
  const registryEntry = registryById.get(standardId);
  const state = maturityState(standardId);
  const repo = claimedRepoFor(standardId);
  const referenceRow = !repo
    ? 'None cataloged for this standard.'
    : repo.status === 'candidate'
      ? `Not built. \`${repo.id}\` is a catalog candidate, not an existing repository, so no rule on this page has been proven against one.`
      : `${mdLink(repo.repo, repo.url)} (${repo.status}) — see **Reference implementation** below.`;
  const rows = [
    ['Maturity', `**${state.label}**`],
    ['What this state means', state.means],
    ['Full rubric', 'Not authored yet. This page is a charter, not a judgeable standard.'],
    ['Reference implementation', referenceRow],
    ['Blocking promotion', registryEntry?.maturityNote ?? 'Not recorded.']
  ];
  return `
| Charter status | Value |
|---|---|
${rows.map(([label, value]) => `| ${label} | ${value} |`).join('\n')}

Maturity states are defined in [Standards Authoring](../authoring.md#planned-charter-maturity-states).
Metadata lives in [\`standards/registry.json\`](https://github.com/vibecodeqa/vibecodeqa/blob/main/standards/registry.json).
`;
}

function generatedStackIndex() {
  const authored = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const crossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));
  const aliases = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isAliasOnly(standard));
  const planned = plannedStandards().filter((standard) => standard.docsUrl);

  return `
## Authored Stack Rubrics

${authored.map((standard) => {
  const registryEntry = registryById.get(standard.id);
  const charter = relativeDocsUrl(standard.docsUrl, 'stacks');
  return `- ${mdLink(standardTitle(standard.id), charter)}: ${registryEntry?.summary ?? standard.ownedRules.join(', ')} Full rubric: ${mdLink(`${standardTitle(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))}.`;
}).join('\n')}

## Authored Cross-Cutting Rubrics

Cross-cutting rubrics are authored standards too, but they are cataloged through item pages because they apply across many stack shapes rather than defining a deployable stack by themselves.

${crossCutting.map((standard) => `- ${mdLink(`${standardTitle(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))}: cataloged from ${mdLink('item page', relativeDocsUrl(standard.docsUrl, 'stacks'))}.`).join('\n')}

## Published Aliases

${aliases.map((standard) => `- \`${standard.id}\`: resolves to ${mdLink(normalizeStandardUrl(standard.standardUrl), normalizeStandardUrl(standard.standardUrl))}.`).join('\n') || '- None.'}

## Planned Stack Charters

Planned charters are ranked by [maturity state](../authoring.md#planned-charter-maturity-states),
not listed as one undifferentiated backlog. A charter's state says how close it is to a
versioned rubric, and every charter page carries the reason for its own state.

${plannedByMaturity(planned)}
`;
}

// Grouped rather than flat: a charter with governed candidate rules and a published
// reference repo is not the same artifact as one whose only cited consumer is archived,
// and a single "Planned" list said they were.
function plannedByMaturity(planned) {
  const order = ['candidate-rubric', 'draft-charter', 'backlog'];
  return order
    .map((maturity) => {
      const group = planned.filter((standard) => maturityOf(standard.id) === maturity);
      if (!group.length) return null;
      const state = maturityStates[maturity];
      const lines = group.map((standard) => `- ${mdLink(standardTitle(standard.id), relativeDocsUrl(standard.docsUrl, 'stacks'))}: ${standard.ownedRules.join(', ')}.`);
      return `### ${state.label}\n\n${state.means}\n\n${lines.join('\n')}`;
    })
    .filter(Boolean)
    .join('\n\n');
}

function generatedItemsIndex() {
  const groups = new Map();
  for (const item of compositions.stackItems) {
    if (!groups.has(item.kind)) groups.set(item.kind, []);
    groups.get(item.kind).push(item);
  }
  return [...groups.entries()].map(([kind, items]) => {
    const lines = items.map((item) => `- ${mdLink(item.title, relativeDocsUrl(item.docsUrl, 'items'))}: ${item.vcqaShouldOwn.join(', ')}.`);
    return `## ${titleize(kind)}\n\n${lines.join('\n')}`;
  }).join('\n\n');
}

function generatedCompositionsSummary() {
  const rows = compositions.composedStandards.map((standard) => {
    const docs = relativeDocsUrl(standard.docsUrl, '.');
    const full = standard.standardUrl ? mdLink(standard.latestEdition, normalizeStandardUrl(standard.standardUrl)) : 'planned';
    return `| ${docs ? mdLink(standardTitle(standard.id), docs) : standardTitle(standard.id)} | ${standard.status} | ${maturityState(standard.id).label} | ${full} | ${standard.stackItems.map((id) => `\`${id}\``).join(', ')} |`;
  });
  return `
| Standard | Status | Maturity | Edition | Composes |
|---|---|---|---|---|
${rows.join('\n')}
`;
}

function referenceVersionPolicy(reference) {
  if (reference.versionPolicy) return reference.versionPolicy;
  if (/\/cli\/v\d+\//.test(reference.url)) {
    const version = reference.url.match(/\/cli\/(v\d+)\//)?.[1];
    return `Pinned to ${version} upstream docs.`;
  }
  if (/\/specification\/\d{4}-\d{2}-\d{2}/.test(reference.url)) {
    const version = reference.url.match(/\/specification\/(\d{4}-\d{2}-\d{2})/)?.[1];
    return `Pinned to dated specification ${version}.`;
  }
  return 'Tracks current canonical upstream URL.';
}

function generatedReferencesPage() {
  const linkRule = references.policy?.linkHealth?.rule ?? 'Primary-source URLs are checked in CI.';
  const versioningRule = references.policy?.linkHealth?.versioningRule;
  const appliesRule = references.policy?.appliesToRule ?? '`appliesTo` uses canonical VCQA IDs; `topics` are descriptive.';
  const sourcePreference = references.policy?.sourcePreference ?? [];

  const sections = references.categories.map((category) => {
    const rows = category.references.map((reference) => {
      const appliesTo = reference.appliesTo?.length
        ? reference.appliesTo.map((id) => `\`${id}\``).join(', ')
        : '-';
      const topics = reference.topics?.length
        ? reference.topics.map((topic) => `\`${topic}\``).join(', ')
        : '-';
      const redirect = reference.expectedRedirectUrl
        ? mdLink('expected redirect', reference.expectedRedirectUrl)
        : 'none expected';
      const useFor = reference.useFor.join('; ');
      return `| ${mdLink(reference.title, reference.url)} | ${reference.publisher} | ${referenceVersionPolicy(reference)} | CI-enforced 2xx | ${redirect} | ${appliesTo} | ${topics} | ${useFor} |`;
    });

    return `## ${category.title}

${category.description}

| Reference | Publisher | Version policy | Link check | Redirect target | Controlled appliesTo | Topics | Use it for |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}`;
  }).join('\n\n');

  return `# Standards References

This is the authority map for VibeCode QA standards. These are the official specs,
framework docs, platform docs, security standards, and testing guides we cite before
writing stack-specific rubrics.

The machine-readable version lives at
[\`/standards/references.json\`](/standards/references.json). Schema:
[\`/standards/references.schema.json\`](/standards/references.schema.json).

## Registry status

- Last reviewed: **${references.lastReviewed}**
- Link health: **${references.policy?.linkHealth?.status ?? 'checked-in-ci'}**
- Link rule: ${linkRule}
${versioningRule ? `- Versioning rule: ${versioningRule}\n` : ''}- Applicability rule: ${appliesRule}

## Authoring rule

${references.policy?.authoringRule ?? 'Do not re-create broad framework doctrine when an upstream standard already exists.'}

## Source preference

${sourcePreference.map((source) => `- ${source}`).join('\n')}

${sections}
`;
}

function generatedHtmlPublishedRubrics() {
  return compositions.composedStandards
    .filter((standard) => isComposedAuthored(standard) && !isAliasOnly(standard))
    .map((standard) => {
      const registryEntry = registryById.get(standard.id);
      const edition = editionLabel(registryEntry) ?? standard.latestEdition;
      return `<tr><td>${htmlLink(standard.id, normalizeStandardUrl(standard.standardUrl), 'name')}</td><td>${escapeHtml(registryEntry?.summary ?? standard.ownedRules.join(', '))}</td><td><span class="badge live">${escapeHtml(edition)} · LIVE</span></td></tr>`;
    })
    .join('\n');
}

function generatedHtmlReferenceRepos() {
  const rows = [...reposByStatus('published'), ...reposByStatus('experimental')]
    .map((repo) => `<tr><td>${htmlLink(repo.id, repo.url, 'name')}</td><td>${escapeHtml(repo.status)}</td><td>${escapeHtml(repo.demonstrates)}</td><td>${evidenceHtml(repo)}</td></tr>`)
    .join('\n');
  const next = reposByStatus('candidate')
    .map((repo) => `<code>${escapeHtml(repo.id)}</code>`)
    .join(', ');
  const notes = referenceRepos
    .filter((repo) => repo.note)
    .map((repo) => `<p><code>${escapeHtml(repo.id)}</code>: ${escapeHtml(repo.note)}</p>`)
    .join('\n');
  return `<table>
<tr><th>Repository</th><th>Catalog status</th><th>What it demonstrates</th><th>Score evidence</th></tr>
${rows}
</table>
<p>Scores marked <em>self-reported</em> come from the reference repo's own tracked VCQA report at the listed commit. They are claims with a visible provenance trail, not independent assessments.</p>
${notes}
<p>Next candidates: ${next}.</p>`;
}

function generatedHtmlNextStandards() {
  return plannedStandards()
    .slice()
    .sort(byMaturity)
    .map((standard) => {
      const label = standard.docsUrl ? htmlLink(standard.id, normalizeStandardUrl(standard.docsUrl), 'name') : `<span class="name">${escapeHtml(standard.id)}</span>`;
      return `<tr><td>${label}</td><td>${escapeHtml(standard.ownedRules.join(', '))}</td><td><span class="badge planned">${escapeHtml(maturityState(standard.id).label.toLowerCase())}</span></td></tr>`;
    })
    .join('\n');
}

function standardKind(standard) {
  if (isAliasOnly(standard)) return 'alias';
  if (standard.status === 'planned') return 'planned';
  if (isStackStandard(standard)) return 'authored-stack';
  return 'authored-cross-cutting';
}

function chipFor(id, optional = false) {
  const item = compositions.stackItems.find((entry) => entry.id === id);
  const standard = compositions.composedStandards.find((entry) => entry.id === id);
  const href = normalizeStandardUrl(item?.docsUrl ?? standard?.docsUrl);
  const cls = item ? 'item' : 'standard';
  const optionalClass = optional ? ' optional' : '';
  if (!href) return `<span class="chip ${cls}${optionalClass}">${escapeHtml(id)}</span>`;
  return `<a class="chip ${cls}${optionalClass}" href="${escapeHtml(href)}">${escapeHtml(id)}</a>`;
}

function markdownEntityLink(id) {
  const item = compositions.stackItems.find((entry) => entry.id === id);
  const standard = compositions.composedStandards.find((entry) => entry.id === id);
  const href = normalizeStandardUrl(item?.docsUrl ?? standard?.docsUrl ?? standard?.standardUrl);
  return href ? mdLink(id, href) : `\`${id}\``;
}

function graphModel() {
  const standards = compositions.composedStandards.map((standard) => ({
    id: standard.id,
    title: standardTitle(standard.id),
    kind: standardKind(standard),
    status: standard.status,
    maturity: maturityOf(standard.id),
    docsUrl: normalizeStandardUrl(standard.docsUrl),
    standardUrl: normalizeStandardUrl(standard.standardUrl),
    latestEdition: standard.latestEdition,
    stackItems: standard.stackItems ?? [],
    optionalStackItems: standard.optionalStackItems ?? [],
    aliases: standard.aliases ?? [],
    ownedRules: standard.ownedRules ?? []
  }));
  const items = compositions.stackItems.map((item) => ({
    id: item.id,
    title: item.title,
    kind: item.kind,
    docsUrl: normalizeStandardUrl(item.docsUrl),
    references: item.references ?? []
  }));
  const referenceImplementations = referenceRepos.map((repo) => ({
    id: repo.id,
    repo: repo.repo,
    url: repo.url,
    status: repo.status,
    standards: repo.standards ?? [],
    demonstratesPrimary: repo.demonstratesPrimary ?? null,
    note: repo.note ?? null,
    evidence: repo.evidence
      ? { ...repo.evidence, verification: verificationLabel(repo.evidence) }
      : null
  }));
  const edges = [
    ...standards.flatMap((standard) => [
      ...standard.stackItems.map((item) => ({ from: item, to: standard.id, type: 'composes' })),
      ...standard.optionalStackItems.map((item) => ({ from: item, to: standard.id, type: 'optional' }))
    ]),
    ...referenceImplementations.flatMap((repo) => (repo.standards ?? []).map((standard) => ({
      from: repo.id,
      to: standard,
      type: 'demonstrates'
    }))),
    ...standards.filter((standard) => standard.kind === 'alias').map((standard) => ({
      from: standard.id,
      to: standard.standardUrl,
      type: 'aliases'
    }))
  ];
  return { version: 1, source: 'standards/compositions.json', standards, items, referenceImplementations, edges };
}

function generatedGraphContent() {
  const model = graphModel();
  const groups = [
    ['Authored Stack Rubrics', model.standards.filter((standard) => standard.kind === 'authored-stack'), 'authored'],
    ['Authored Cross-Cutting Rubrics', model.standards.filter((standard) => standard.kind === 'authored-cross-cutting'), 'crosscut'],
    ['Published Aliases', model.standards.filter((standard) => standard.kind === 'alias'), 'authored'],
    ['Planned Standards', model.standards.filter((standard) => standard.kind === 'planned'), 'planned']
  ];
  const standardCards = groups.map(([heading, standards, cls]) => `
<h2 id="${heading.toLowerCase().replaceAll(' ', '-')}">${heading}</h2>

<div class="standard-grid">
${standards.map((standard) => {
  const links = [
    standard.docsUrl ? htmlLink('catalog', standard.docsUrl) : null,
    standard.standardUrl ? htmlLink('rubric', standard.standardUrl) : null
  ].filter(Boolean).join('');
  const chips = [
    ...(standard.stackItems ?? []).map((id) => chipFor(id)),
    ...(standard.optionalStackItems ?? []).map((id) => chipFor(id, true))
  ].join('\n      ');
  const summary = registryById.get(standard.id)?.summary ?? standard.ownedRules.join(', ');
  const edition = standard.latestEdition ? ` ${standard.latestEdition}` : '';
  return `  <div class="standard-card ${cls}">
    <div class="title"><strong>${standard.docsUrl ? htmlLink(standard.id, standard.docsUrl) : escapeHtml(standard.id)}</strong><span class="status">${escapeHtml(standard.status)}${escapeHtml(edition)}</span></div>
    <div class="kind">${escapeHtml(summary)}</div>
    <div class="chips">
      ${chips || '<span class="chip">metadata-only</span>'}
    </div>
    <div class="links">${links}</div>
  </div>`;
}).join('\n')}
</div>`).join('\n\n');

  const templates = referenceRepos.map((repo) => `  <div class="node template">
    <div class="title"><strong>${htmlLink(repo.id, repo.url)}</strong><span class="status">${escapeHtml(repo.status)}</span></div>
    <div class="chips">${(repo.standards ?? []).map((id) => chipFor(id)).join('')}</div>
    <div class="links">${evidenceHtml(repo)}</div>
  </div>`).join('\n');

  const itemGroups = new Map();
  for (const item of model.items) {
    if (!itemGroups.has(item.kind)) itemGroups.set(item.kind, []);
    itemGroups.get(item.kind).push(item);
  }
  const items = [...itemGroups.entries()].map(([kind, group]) => {
    const chips = group.map((item) => item.docsUrl ? `<a class="chip item" href="${escapeHtml(item.docsUrl)}">${escapeHtml(item.id)}</a>` : `<span class="chip item">${escapeHtml(item.id)}</span>`).join('');
    return `  <div class="item-card"><strong>${escapeHtml(titleize(kind))}</strong><div class="chips">${chips}</div></div>`;
  }).join('\n');

  return `
<div class="legend">
  <div class="node authored"><strong>Authored stack rubric</strong><br><span class="kind">Deployable stack standard with stable rule IDs.</span></div>
  <div class="node crosscut"><strong>Authored cross-cutting rubric</strong><br><span class="kind">First-class rubric applied across stack shapes.</span></div>
  <div class="node planned"><strong>Planned standard</strong><br><span class="kind">Cataloged rule surface; full rubric is not published yet.</span></div>
  <div class="node item"><strong>Stack item leaf</strong><br><span class="kind">Framework, runtime, tool, protocol, quality, or supply-chain layer.</span></div>
  <div class="node template"><strong>Reference template</strong><br><span class="kind">Runnable repo with CI and a tracked VCQA report.</span></div>
</div>

<p class="kind">Generated graph data: <a href="/standards/graph.json"><code>graph.json</code></a>.</p>

<h2 id="reference-templates">Reference Templates</h2>

<div class="template-row">
${templates}
</div>

${standardCards}

<h2 id="stack-item-leaves">Stack Item Leaves</h2>

<div class="item-grid">
${items}
</div>
`;
}

function standardsUsing(id, selfId) {
  return compositions.composedStandards
    .filter((standard) => standard.id !== selfId)
    .filter((standard) => (standard.stackItems ?? []).includes(id) || (standard.optionalStackItems ?? []).includes(id));
}

function relatedStandardsFor(standard) {
  const direct = new Map();
  for (const item of [...(standard.stackItems ?? []), ...(standard.optionalStackItems ?? [])]) {
    for (const related of standardsUsing(item, standard.id)) {
      if (!isAliasOnly(related)) direct.set(related.id, related);
    }
  }
  for (const id of registryById.get(standard.id)?.recommends ?? []) {
    const related = compositions.composedStandards.find((entry) => entry.id === id);
    if (related && !isAliasOnly(related)) direct.set(related.id, related);
  }
  return [...direct.values()].slice(0, 8);
}

function generatedRelatedSection(standard) {
  const registryEntry = registryById.get(standard.id);
  const latest = registryEntry?.editions?.find((edition) => edition.status === 'latest');
  const templates = compositions.referenceImplementations.filter((repo) => (repo.standards ?? []).includes(standard.id));
  const related = relatedStandardsFor(standard);
  const composed = [
    ...(standard.stackItems ?? []).map((id) => markdownEntityLink(id)),
    ...(standard.optionalStackItems ?? []).map((id) => `${markdownEntityLink(id)} (optional)`)
  ].join(', ');
  const lifecycle = latest?.lifecycle;
  const lifecycleText = lifecycle
    ? `Edition lifecycle: ${lifecycle.deprecated ? 'deprecated' : 'active'}${lifecycle.supersededBy ? `, superseded by ${lifecycle.supersededBy}` : ''}. Errata: ${lifecycle.errata.length ? lifecycle.errata.join('; ') : 'none'}.`
    : 'Edition lifecycle metadata is unavailable.';

  return `
## Related Standards

Reports and scans should cite this pinned edition URL:
<${registryEntry?.standardUrl ?? standard.standardUrl}>

- Catalog page: ${standard.docsUrl ? mdLink(standard.docsUrl, normalizeStandardUrl(standard.docsUrl)) : 'none'}
- Latest edition: \`${standard.latestEdition}\`
- ${lifecycleText}
- Composes: ${composed || 'metadata-only'}
- Reference implementations: ${templates.length ? templates.map((repo) => mdLink(repo.id, repo.url)).join(', ') : 'none yet'}
- Related standards: ${related.length ? related.map((entry) => entry.standardUrl ? mdLink(entry.id, normalizeStandardUrl(entry.standardUrl)) : (entry.docsUrl ? mdLink(entry.id, normalizeStandardUrl(entry.docsUrl)) : `\`${entry.id}\``)).join(', ') : 'none'}
`;
}

// Charter pages that carry a generated reference-evidence block: every stack page whose
// standard has a primary reference repo with score evidence. Deduped by page, because an
// alias standard can point at the same charter page.
function stackPagesWithReferenceEvidence() {
  const seen = new Set();
  return compositions.composedStandards.flatMap((standard) => {
    const slug = docsPageSlug(standard.docsUrl, 'stacks');
    if (!slug || seen.has(slug) || !primaryRepoFor(standard.id)) return [];
    seen.add(slug);
    return [{ id: standard.id, slug }];
  });
}

// Planned stack charter pages, deduped by page: the pages that carry a generated
// charter-status block instead of a hand-typed "Status: Planned charter" line.
function plannedStackCharterPages() {
  const seen = new Set();
  return compositions.composedStandards.flatMap((standard) => {
    if (standard.status !== 'planned' || !isStackStandard(standard)) return [];
    const slug = docsPageSlug(standard.docsUrl, 'stacks');
    if (!slug || seen.has(slug)) return [];
    seen.add(slug);
    return [{ id: standard.id, slug }];
  });
}

// Authored stack charter pages, deduped by page: the pages the authored-charter bar in
// docs/docs/standards/authoring.md applies to.
function authoredStackCharterPages() {
  const seen = new Set();
  return compositions.composedStandards.flatMap((standard) => {
    if (!isComposedAuthored(standard) || !isStackStandard(standard)) return [];
    const slug = docsPageSlug(standard.docsUrl, 'stacks');
    if (!slug || seen.has(slug)) return [];
    seen.add(slug);
    return [{ id: standard.id, slug }];
  });
}

const changed = [
  writeJsonIfChanged('standards/graph.json', graphModel()),
  replaceGeneratedBlock('docs/docs/standards/index.md', 'standards-inventory', generatedStandardsCatalog()),
  replaceGeneratedBlock('docs/docs/standards/index.md', 'reference-implementations', generatedReferenceRepos()),
  replaceGeneratedBlock('docs/docs/standards/compositions.md', 'reference-implementations', generatedCompositionsReferenceRepos()),
  ...stackPagesWithReferenceEvidence().map((page) =>
    replaceGeneratedBlock(`docs/docs/standards/stacks/${page.slug}.md`, 'reference-evidence', generatedStackReferenceEvidence(page.id))),
  ...authoredStackCharterPages().map((page) =>
    replaceGeneratedBlock(`docs/docs/standards/stacks/${page.slug}.md`, 'charter-maintenance', generatedCharterMaintenance(page.id))),
  ...plannedStackCharterPages().map((page) =>
    replaceGeneratedBlock(`docs/docs/standards/stacks/${page.slug}.md`, 'charter-status', generatedCharterStatus(page.id))),
  replaceGeneratedBlock('docs/docs/standards/stacks/index.md', 'stack-standards-inventory', generatedStackIndex()),
  replaceGeneratedBlock('docs/docs/standards/items/index.md', 'stack-items-inventory', generatedItemsIndex()),
  replaceGeneratedBlock('docs/docs/standards/compositions.md', 'composition-summary', generatedCompositionsSummary()),
  replaceGeneratedBlock('docs/docs/standards/graph.md', 'standards-graph', generatedGraphContent()),
  replaceGeneratedBlock('docs/docs/stacks.md', 'authored-rubrics', generatedStacksPageRubrics()),
  writeIfChanged('docs/docs/standards/references.md', generatedReferencesPage()),
  replaceGeneratedTomlBlock('docs/zensical.toml', 'nav-stack-standards', generatedNavStackStandards(), '      '),
  replaceGeneratedTomlBlock('docs/zensical.toml', 'nav-stack-items', generatedNavStackItems(), '      '),
  replaceGeneratedTomlBlock('docs/zensical.toml', 'nav-assessments', generatedNavAssessments(), '      '),
  replaceGeneratedBlock('standards/index.html', 'published-rubrics', generatedHtmlPublishedRubrics()),
  replaceGeneratedBlock('standards/index.html', 'reference-implementations', generatedHtmlReferenceRepos()),
  replaceGeneratedBlock('standards/index.html', 'next-standards', generatedHtmlNextStandards()),
  ...compositions.composedStandards
    .filter((standard) => isComposedAuthored(standard) && !isAliasOnly(standard))
    .map((standard) => replaceGeneratedBlock(`standards/${standard.id}/docs/v1/index.md`, 'related-standards', generatedRelatedSection(standard)))
].filter(Boolean);

if (checkOnly && changed.length) {
  process.exit(1);
}

if (!checkOnly) {
  console.log(changed.length ? `Updated ${changed.length} generated catalog block(s)` : 'Generated catalog blocks are current');
}
