#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(readFileSync(join(root, 'standards/registry.json'), 'utf8'));
const compositions = JSON.parse(readFileSync(join(root, 'standards/compositions.json'), 'utf8'));
const checkOnly = process.argv.includes('--check');
const generatedBy = '<!-- Generated by standards/generate-catalog.mjs; edit standards/*.json instead. -->';

const registryById = new Map(registry.standards.map((standard) => [standard.id, standard]));
const titleWords = new Map([
  ['api', 'API'],
  ['cf', 'CF'],
  ['ci', 'CI'],
  ['cli', 'CLI'],
  ['d1', 'D1'],
  ['github', 'GitHub'],
  ['kb', 'KB'],
  ['mcp', 'MCP'],
  ['openapi', 'OpenAPI'],
  ['saas', 'SaaS'],
  ['sdk', 'SDK'],
  ['spa', 'SPA'],
  ['typescript', 'TypeScript'],
  ['vscode', 'VS Code']
]);

const titleize = (id) => id.split('-').map((part) => titleWords.get(part) ?? part.charAt(0).toUpperCase() + part.slice(1)).join(' ');

const mdLink = (label, href) => `[${label}](${href})`;
const htmlLink = (label, href, cls = '') => `<a href="${escapeHtml(href)}"${cls ? ` class="${cls}"` : ''}>${escapeHtml(label)}</a>`;

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function normalizeStandardUrl(url) {
  return url ? url.replace(/^https:\/\/vibecodeqa\.online/, '') : null;
}

function relativeDocsUrl(url, fromDir) {
  if (!url) return null;
  const clean = url.replace(/^https:\/\/vibecodeqa\.online/, '').replace(/^\/docs\/standards\//, '');
  const noSlash = clean.replace(/\/$/, '');
  if (!noSlash) return 'index.md';
  const target = join(root, 'docs/docs/standards', `${noSlash}.md`);
  const source = join(root, 'docs/docs/standards', fromDir);
  return relative(source, target).replaceAll('\\', '/');
}

function editionLabel(standard) {
  const latest = standard.editions?.find((edition) => edition.status === 'latest');
  return latest?.version ?? null;
}

function isComposedAuthored(composed) {
  return composed.status === 'authored' && normalizeStandardUrl(composed.standardUrl);
}

function isAliasOnly(composed) {
  const standardUrl = normalizeStandardUrl(composed.standardUrl);
  return Boolean(standardUrl && !standardUrl.includes(`/standards/${composed.id}/`));
}

function isStackStandard(composed) {
  return Boolean(composed.docsUrl?.includes('/stacks/') && !isAliasOnly(composed));
}

function plannedStandards() {
  const composedIds = new Set(compositions.composedStandards.map((standard) => standard.id));
  const compositionPlanned = compositions.composedStandards.filter((standard) => standard.status === 'planned');
  const registryOnly = registry.standards
    .filter((standard) => standard.status === 'planned' && !composedIds.has(standard.id))
    .filter((standard) => standard.docsUrl || standard.type === 'cross-cutting')
    .map((standard) => ({
      id: standard.id,
      status: 'planned',
      aliases: standard.aliases ?? [],
      stackItems: standard.composes ?? [],
      ownedRules: [standard.summary],
      benefits: [],
      docsUrl: standard.docsUrl,
      standardUrl: null,
      latestEdition: null
    }));
  return [...compositionPlanned, ...registryOnly];
}

function writeIfChanged(path, next) {
  const abs = join(root, path);
  const current = readFileSync(abs, 'utf8');
  if (current === next) return false;
  if (checkOnly) {
    console.error(`${path} is stale; run node standards/generate-catalog.mjs`);
    return true;
  }
  writeFileSync(abs, next);
  return true;
}

function replaceGeneratedBlock(path, blockName, body) {
  const abs = join(root, path);
  const current = readFileSync(abs, 'utf8');
  const start = `<!-- BEGIN GENERATED:${blockName} -->`;
  const end = `<!-- END GENERATED:${blockName} -->`;
  const pattern = new RegExp(`${escapeRegex(start)}[\\s\\S]*?${escapeRegex(end)}`);
  if (!pattern.test(current)) {
    throw new Error(`${path}: missing generated block ${blockName}`);
  }
  const next = current.replace(pattern, `${start}\n${generatedBy}\n${body.trim()}\n${end}`);
  return writeIfChanged(path, next);
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function generatedStandardsCatalog() {
  const authoredStack = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const authoredCrossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));
  const aliases = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isAliasOnly(standard));
  const planned = plannedStandards();

  const stackRows = authoredStack.map((standard) => {
    const registryEntry = registryById.get(standard.id);
    const aliases = standard.aliases.length ? ` \`${standard.aliases.join('`, `')}\`` : '';
    return `| ${titleize(standard.id)}${aliases} | ${mdLink('Charter', relativeDocsUrl(standard.docsUrl, '.'))} | ${mdLink(`${titleize(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))} | ${registryEntry?.summary ?? standard.ownedRules.join(', ')} |`;
  });

  const crossRows = authoredCrossCutting.map((standard) => {
    const catalog = relativeDocsUrl(standard.docsUrl, '.');
    const label = titleize(standard.id);
    return `| ${label} | ${catalog ? mdLink('Catalog page', catalog) : '-'} | ${mdLink(`${label} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))} | ${standard.ownedRules.slice(0, 3).join('; ')} |`;
  });

  const plannedRows = planned.map((standard) => {
    const catalog = relativeDocsUrl(standard.docsUrl, '.');
    return `| ${catalog ? mdLink(titleize(standard.id), catalog) : titleize(standard.id)} | ${standard.stackItems.map((id) => titleize(id)).join(', ') || '-'} | ${standard.ownedRules.join('; ')} |`;
  });

  const aliasRows = aliases.map((standard) => {
    const target = mdLink(normalizeStandardUrl(standard.standardUrl), normalizeStandardUrl(standard.standardUrl));
    return `- \`${standard.id}\` resolves to ${target}. Aliases: ${standard.aliases.map((alias) => `\`${alias}\``).join(', ') || 'none'}.`;
  });

  return `
## Authored Stack Rubrics

| Stack standard | Charter | Full rubric | What it judges |
|---|---|---|---|
${stackRows.join('\n')}

## Authored Cross-Cutting Rubrics

| Cross-cutting standard | Catalog page | Full rubric | VCQA-owned surface |
|---|---|---|---|
${crossRows.join('\n')}

## Published Aliases

${aliasRows.join('\n') || '- None.'}

## Planned Standards

| Planned standard | Composes | VCQA-owned surface |
|---|---|---|
${plannedRows.join('\n')}
`;
}

function generatedReferenceRepos() {
  const published = compositions.referenceImplementations.filter((repo) => repo.status === 'published');
  const candidates = compositions.referenceImplementations.filter((repo) => repo.status === 'candidate');
  const rows = published.map((repo) => {
    const report = repo.reportUrl ? mdLink(repo.score ? `${repo.score} report` : 'Report', repo.reportUrl) : '-';
    return `| ${mdLink(repo.repo, repo.url)} | ${repo.standards?.map((id) => `\`${id}\``).join(', ') ?? '-'} | ${repo.demonstrates} | ${report}; CI ${repo.ci ?? 'unknown'} |`;
  });
  const next = candidates.map((repo) => `- \`${repo.id}\`: ${repo.demonstrates}`).join('\n');

  return `
| Repository | Standards demonstrated | What it demonstrates | Evidence |
|---|---|---|---|
${rows.join('\n')}

Next template candidates:

${next}
`;
}

function generatedStackIndex() {
  const authored = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const crossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));
  const aliases = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isAliasOnly(standard));
  const planned = plannedStandards().filter((standard) => standard.docsUrl);

  return `
## Authored Stack Rubrics

${authored.map((standard) => {
  const registryEntry = registryById.get(standard.id);
  const charter = relativeDocsUrl(standard.docsUrl, 'stacks');
  return `- ${mdLink(titleize(standard.id), charter)}: ${registryEntry?.summary ?? standard.ownedRules.join(', ')} Full rubric: ${mdLink(`${titleize(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))}.`;
}).join('\n')}

## Authored Cross-Cutting Rubrics

Cross-cutting rubrics are authored standards too, but they are cataloged through item pages because they apply across many stack shapes rather than defining a deployable stack by themselves.

${crossCutting.map((standard) => `- ${mdLink(`${titleize(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))}: cataloged from ${mdLink('item page', relativeDocsUrl(standard.docsUrl, 'stacks'))}.`).join('\n')}

## Published Aliases

${aliases.map((standard) => `- \`${standard.id}\`: resolves to ${mdLink(normalizeStandardUrl(standard.standardUrl), normalizeStandardUrl(standard.standardUrl))}.`).join('\n') || '- None.'}

## Planned Stack Charters

${planned.map((standard) => `- ${mdLink(titleize(standard.id), relativeDocsUrl(standard.docsUrl, 'stacks'))}: ${standard.ownedRules.join(', ')}.`).join('\n')}
`;
}

function generatedItemsIndex() {
  const groups = new Map();
  for (const item of compositions.stackItems) {
    if (!groups.has(item.kind)) groups.set(item.kind, []);
    groups.get(item.kind).push(item);
  }
  return [...groups.entries()].map(([kind, items]) => {
    const lines = items.map((item) => `- ${mdLink(titleize(item.id), relativeDocsUrl(item.docsUrl, 'items'))}: ${item.vcqaShouldOwn.join(', ')}.`);
    return `## ${titleize(kind)}\n\n${lines.join('\n')}`;
  }).join('\n\n');
}

function generatedCompositionsSummary() {
  const rows = compositions.composedStandards.map((standard) => {
    const docs = relativeDocsUrl(standard.docsUrl, '.');
    const full = standard.standardUrl ? mdLink(standard.latestEdition, normalizeStandardUrl(standard.standardUrl)) : 'planned';
    return `| ${docs ? mdLink(titleize(standard.id), docs) : titleize(standard.id)} | ${standard.status} | ${full} | ${standard.stackItems.map((id) => `\`${id}\``).join(', ')} |`;
  });
  return `
| Standard | Status | Edition | Composes |
|---|---|---|---|
${rows.join('\n')}
`;
}

function generatedHtmlPublishedRubrics() {
  return compositions.composedStandards
    .filter((standard) => isComposedAuthored(standard) && !isAliasOnly(standard))
    .map((standard) => {
      const registryEntry = registryById.get(standard.id);
      const edition = editionLabel(registryEntry) ?? standard.latestEdition;
      return `<tr><td>${htmlLink(standard.id, normalizeStandardUrl(standard.standardUrl), 'name')}</td><td>${escapeHtml(registryEntry?.summary ?? standard.ownedRules.join(', '))}</td><td><span class="badge live">${escapeHtml(edition)} · LIVE</span></td></tr>`;
    })
    .join('\n');
}

function generatedHtmlReferenceRepos() {
  const rows = compositions.referenceImplementations
    .filter((repo) => repo.status === 'published')
    .map((repo) => {
      const evidence = repo.reportUrl ? `${htmlLink(repo.score ? `${repo.score} report` : 'Report', repo.reportUrl)}; CI ${escapeHtml(repo.ci ?? 'unknown')}.` : 'No report yet.';
      return `<tr><td>${htmlLink(repo.id, repo.url, 'name')}</td><td>${escapeHtml(repo.demonstrates)}</td><td>${evidence}</td></tr>`;
    })
    .join('\n');
  const next = compositions.referenceImplementations
    .filter((repo) => repo.status === 'candidate')
    .map((repo) => `<code>${escapeHtml(repo.id)}</code>`)
    .join(', ');
  return `<table>
<tr><th>Repository</th><th>What it demonstrates</th><th>Score evidence</th></tr>
${rows}
</table>
<p>Next candidates: ${next}.</p>`;
}

function generatedHtmlNextStandards() {
  return plannedStandards()
    .map((standard) => {
      const label = standard.docsUrl ? htmlLink(standard.id, normalizeStandardUrl(standard.docsUrl), 'name') : `<span class="name">${escapeHtml(standard.id)}</span>`;
      return `<tr><td>${label}</td><td>${escapeHtml(standard.ownedRules.join(', '))}</td><td><span class="badge planned">planned</span></td></tr>`;
    })
    .join('\n');
}

const changed = [
  replaceGeneratedBlock('docs/docs/standards/index.md', 'standards-inventory', generatedStandardsCatalog()),
  replaceGeneratedBlock('docs/docs/standards/index.md', 'reference-implementations', generatedReferenceRepos()),
  replaceGeneratedBlock('docs/docs/standards/stacks/index.md', 'stack-standards-inventory', generatedStackIndex()),
  replaceGeneratedBlock('docs/docs/standards/items/index.md', 'stack-items-inventory', generatedItemsIndex()),
  replaceGeneratedBlock('docs/docs/standards/compositions.md', 'composition-summary', generatedCompositionsSummary()),
  replaceGeneratedBlock('standards/index.html', 'published-rubrics', generatedHtmlPublishedRubrics()),
  replaceGeneratedBlock('standards/index.html', 'reference-implementations', generatedHtmlReferenceRepos()),
  replaceGeneratedBlock('standards/index.html', 'next-standards', generatedHtmlNextStandards())
].filter(Boolean);

if (checkOnly && changed.length) {
  process.exit(1);
}

if (!checkOnly) {
  console.log(changed.length ? `Updated ${changed.length} generated catalog block(s)` : 'Generated catalog blocks are current');
}
