#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(readFileSync(join(root, 'standards/registry.json'), 'utf8'));
const compositions = JSON.parse(readFileSync(join(root, 'standards/compositions.json'), 'utf8'));
const references = JSON.parse(readFileSync(join(root, 'standards/references.json'), 'utf8'));
const checkOnly = process.argv.includes('--check');
const generatedBy = '<!-- Generated by standards/generate-catalog.mjs; edit standards/*.json instead. -->';

const registryById = new Map(registry.standards.map((standard) => [standard.id, standard]));
const titleWords = new Map([
  ['api', 'API'],
  ['cf', 'CF'],
  ['ci', 'CI'],
  ['cli', 'CLI'],
  ['d1', 'D1'],
  ['github', 'GitHub'],
  ['kb', 'KB'],
  ['mcp', 'MCP'],
  ['openapi', 'OpenAPI'],
  ['saas', 'SaaS'],
  ['sdk', 'SDK'],
  ['spa', 'SPA'],
  ['typescript', 'TypeScript'],
  ['vscode', 'VS Code']
]);

const titleize = (id) => id.split('-').map((part) => titleWords.get(part) ?? part.charAt(0).toUpperCase() + part.slice(1)).join(' ');

const itemById = new Map(compositions.stackItems.map((item) => [item.id, item]));

// Display names come from metadata, never from a heuristic: registry.json owns standard
// titles, compositions.json owns stack item titles. titleize() survives only as a fallback
// for grouping keys such as stack item kinds, which have no metadata entry of their own.
const standardTitle = (id) => registryById.get(id)?.title ?? titleize(id);
const itemTitle = (id) => itemById.get(id)?.title ?? titleize(id);
const entityTitle = (id) => registryById.get(id)?.title ?? itemById.get(id)?.title ?? titleize(id);

const mdLink = (label, href) => `[${label}](${href})`;
const htmlLink = (label, href, cls = '') => `<a href="${escapeHtml(href)}"${cls ? ` class="${cls}"` : ''}>${escapeHtml(label)}</a>`;

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function normalizeStandardUrl(url) {
  return url ? url.replace(/^https:\/\/vibecodeqa\.online/, '') : null;
}

function relativeDocsUrl(url, fromDir) {
  if (!url) return null;
  const clean = url.replace(/^https:\/\/vibecodeqa\.online/, '').replace(/^\/docs\/standards\//, '');
  const noSlash = clean.replace(/\/$/, '');
  if (!noSlash) return 'index.md';
  const target = join(root, 'docs/docs/standards', `${noSlash}.md`);
  const source = join(root, 'docs/docs/standards', fromDir);
  return relative(source, target).replaceAll('\\', '/');
}

function editionLabel(standard) {
  const latest = standard.editions?.find((edition) => edition.status === 'latest');
  return latest?.version ?? null;
}

function isComposedAuthored(composed) {
  return composed.status === 'authored' && normalizeStandardUrl(composed.standardUrl);
}

function isAliasOnly(composed) {
  const standardUrl = normalizeStandardUrl(composed.standardUrl);
  return Boolean(standardUrl && !standardUrl.includes(`/standards/${composed.id}/`));
}

function isStackStandard(composed) {
  return Boolean(composed.docsUrl?.includes('/stacks/') && !isAliasOnly(composed));
}

function plannedStandards() {
  const composedIds = new Set(compositions.composedStandards.map((standard) => standard.id));
  const compositionPlanned = compositions.composedStandards.filter((standard) => standard.status === 'planned');
  const registryOnly = registry.standards
    .filter((standard) => standard.status === 'planned' && !composedIds.has(standard.id))
    .filter((standard) => standard.docsUrl || standard.type === 'cross-cutting')
    .map((standard) => ({
      id: standard.id,
      status: 'planned',
      aliases: standard.aliases ?? [],
      stackItems: standard.composes ?? [],
      ownedRules: [standard.summary],
      benefits: [],
      docsUrl: standard.docsUrl,
      standardUrl: null,
      latestEdition: null
    }));
  return [...compositionPlanned, ...registryOnly];
}

function writeIfChanged(path, next) {
  const abs = join(root, path);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : '';
  if (current === next) return false;
  if (checkOnly) {
    console.error(`${path} is stale; run node standards/generate-catalog.mjs`);
    return true;
  }
  writeFileSync(abs, next);
  return true;
}

function writeJsonIfChanged(path, value) {
  return writeIfChanged(path, `${JSON.stringify(value, null, 2)}\n`);
}

function replaceGeneratedBlock(path, blockName, body) {
  const abs = join(root, path);
  const current = readFileSync(abs, 'utf8');
  const start = `<!-- BEGIN GENERATED:${blockName} -->`;
  const end = `<!-- END GENERATED:${blockName} -->`;
  const pattern = new RegExp(`${escapeRegex(start)}[\\s\\S]*?${escapeRegex(end)}`);
  if (!pattern.test(current)) {
    throw new Error(`${path}: missing generated block ${blockName}`);
  }
  const next = current.replace(pattern, `${start}\n${generatedBy}\n${body.trim()}\n${end}`);
  return writeIfChanged(path, next);
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// TOML has no comment syntax we can reuse from Markdown, so nav blocks are fenced with
// `# BEGIN GENERATED:<name>` / `# END GENERATED:<name>` at the block's own indent level.
function replaceGeneratedTomlBlock(path, blockName, lines, indent) {
  const abs = join(root, path);
  const current = readFileSync(abs, 'utf8');
  const start = `${indent}# BEGIN GENERATED:${blockName}`;
  const end = `${indent}# END GENERATED:${blockName}`;
  const pattern = new RegExp(`${escapeRegex(start)}[\\s\\S]*?${escapeRegex(end)}`);
  if (!pattern.test(current)) {
    throw new Error(`${path}: missing generated block ${blockName}`);
  }
  const body = lines.map((line) => `${indent}${line}`).join('\n');
  const banner = `${indent}# Generated by standards/generate-catalog.mjs; edit standards/*.json instead.`;
  return writeIfChanged(path, current.replace(pattern, `${start}\n${banner}\n${body}\n${end}`));
}

function docsPageSlug(url, section) {
  const normalized = normalizeStandardUrl(url);
  if (!normalized?.startsWith(`/docs/standards/${section}/`)) return null;
  return normalized.replace(`/docs/standards/${section}/`, '').replace(/\/$/, '') || null;
}

// Stack pages in metadata order, aliases included: nav must show every page the catalog
// claims exists, and nothing else.
function navStackPages() {
  const seen = new Set();
  return compositions.composedStandards.flatMap((standard) => {
    const slug = docsPageSlug(standard.docsUrl, 'stacks');
    if (!slug || seen.has(standard.id)) return [];
    seen.add(standard.id);
    return [{ id: standard.id, slug, title: standardTitle(standard.id) }];
  });
}

// Stack items grouped by kind, matching the ordering of the generated items index so the
// sidebar and the index page never disagree about sequence.
function navStackItems() {
  const groups = new Map();
  for (const item of compositions.stackItems) {
    if (!groups.has(item.kind)) groups.set(item.kind, []);
    groups.get(item.kind).push(item);
  }
  return [...groups.values()].flat().flatMap((item) => {
    const slug = docsPageSlug(item.docsUrl, 'items');
    return slug ? [{ id: item.id, slug, title: itemTitle(item.id) }] : [];
  });
}

// Assessment reports are authored files, but which stack pages have one — and in what
// order — is derived from metadata plus on-disk existence.
function navAssessments() {
  const seen = new Set();
  return navStackPages().flatMap((page) => {
    if (seen.has(page.slug)) return [];
    seen.add(page.slug);
    const path = join(root, 'docs/docs/standards/assessments/stacks', `${page.slug}.md`);
    return existsSync(path) ? [page] : [];
  });
}

function navEntry(title, path) {
  return `{ "${title.replaceAll('"', '\\"')}" = "${path}" },`;
}

function generatedNavStackStandards() {
  return [
    navEntry('Index', 'standards/stacks/index.md'),
    ...navStackPages().map((page) => navEntry(page.title, `standards/stacks/${page.slug}.md`))
  ];
}

function generatedNavStackItems() {
  return [
    navEntry('Index', 'standards/items/index.md'),
    ...navStackItems().map((item) => navEntry(item.title, `standards/items/${item.slug}.md`))
  ];
}

function generatedNavAssessments() {
  return [
    navEntry('Index', 'standards/assessments/index.md'),
    ...navAssessments().map((page) => navEntry(page.title, `standards/assessments/stacks/${page.slug}.md`))
  ];
}

function aliasNoteFor(standard) {
  const aliases = compositions.composedStandards.filter((entry) =>
    entry.id !== standard.id &&
    isAliasOnly(entry) &&
    normalizeStandardUrl(entry.standardUrl) === normalizeStandardUrl(standard.standardUrl));
  if (!aliases.length) return '';
  return ` Also cataloged as ${aliases.map((entry) => `\`${entry.id}\``).join(', ')}.`;
}

// The "Supported stacks" docs page repeats the authored-rubric inventory for readers who
// arrive from detection rather than from the standards catalog. Generate it from the same
// metadata so the two inventories cannot disagree.
function generatedStacksPageRubrics() {
  const bullet = (standard) => {
    const registryEntry = registryById.get(standard.id);
    const label = `${standardTitle(standard.id)} ${standard.latestEdition}`;
    return `- ${mdLink(label, normalizeStandardUrl(standard.standardUrl))} - ${registryEntry?.summary ?? standard.ownedRules.join(', ')}${aliasNoteFor(standard)}`;
  };
  const stacks = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const crossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));

  return `
### Authored stack rubrics

${stacks.map(bullet).join('\n')}

### Authored cross-cutting rubrics

${crossCutting.map(bullet).join('\n')}
`;
}

function generatedStandardsCatalog() {
  const authoredStack = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const authoredCrossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));
  const aliases = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isAliasOnly(standard));
  const planned = plannedStandards();

  const stackRows = authoredStack.map((standard) => {
    const registryEntry = registryById.get(standard.id);
    const aliases = standard.aliases.length ? ` \`${standard.aliases.join('`, `')}\`` : '';
    return `| ${standardTitle(standard.id)}${aliases} | ${mdLink('Charter', relativeDocsUrl(standard.docsUrl, '.'))} | ${mdLink(`${standardTitle(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))} | ${registryEntry?.summary ?? standard.ownedRules.join(', ')} |`;
  });

  const crossRows = authoredCrossCutting.map((standard) => {
    const catalog = relativeDocsUrl(standard.docsUrl, '.');
    const label = standardTitle(standard.id);
    return `| ${label} | ${catalog ? mdLink('Catalog page', catalog) : '-'} | ${mdLink(`${label} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))} | ${standard.ownedRules.slice(0, 3).join('; ')} |`;
  });

  const plannedRows = planned.map((standard) => {
    const catalog = relativeDocsUrl(standard.docsUrl, '.');
    return `| ${catalog ? mdLink(standardTitle(standard.id), catalog) : standardTitle(standard.id)} | ${standard.stackItems.map((id) => entityTitle(id)).join(', ') || '-'} | ${standard.ownedRules.join('; ')} |`;
  });

  const aliasRows = aliases.map((standard) => {
    const target = mdLink(normalizeStandardUrl(standard.standardUrl), normalizeStandardUrl(standard.standardUrl));
    return `- \`${standard.id}\` resolves to ${target}. Aliases: ${standard.aliases.map((alias) => `\`${alias}\``).join(', ') || 'none'}.`;
  });

  return `
## Authored Stack Rubrics

| Stack standard | Charter | Full rubric | What it judges |
|---|---|---|---|
${stackRows.join('\n')}

## Authored Cross-Cutting Rubrics

| Cross-cutting standard | Catalog page | Full rubric | VCQA-owned surface |
|---|---|---|---|
${crossRows.join('\n')}

## Published Aliases

${aliasRows.join('\n') || '- None.'}

## Planned Standards

| Planned standard | Composes | VCQA-owned surface |
|---|---|---|
${plannedRows.join('\n')}
`;
}

function generatedReferenceRepos() {
  const published = compositions.referenceImplementations.filter((repo) => repo.status === 'published');
  const candidates = compositions.referenceImplementations.filter((repo) => repo.status === 'candidate');
  const rows = published.map((repo) => {
    const report = repo.reportUrl ? mdLink(repo.score ? `${repo.score} report` : 'Report', repo.reportUrl) : '-';
    return `| ${mdLink(repo.repo, repo.url)} | ${repo.standards?.map((id) => `\`${id}\``).join(', ') ?? '-'} | ${repo.demonstrates} | ${report}; CI ${repo.ci ?? 'unknown'} |`;
  });
  const next = candidates.map((repo) => `- \`${repo.id}\`: ${repo.demonstrates}`).join('\n');

  return `
| Repository | Standards demonstrated | What it demonstrates | Evidence |
|---|---|---|---|
${rows.join('\n')}

Next template candidates:

${next}
`;
}

function generatedStackIndex() {
  const authored = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isStackStandard(standard));
  const crossCutting = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && !isStackStandard(standard) && !isAliasOnly(standard));
  const aliases = compositions.composedStandards.filter((standard) => isComposedAuthored(standard) && isAliasOnly(standard));
  const planned = plannedStandards().filter((standard) => standard.docsUrl);

  return `
## Authored Stack Rubrics

${authored.map((standard) => {
  const registryEntry = registryById.get(standard.id);
  const charter = relativeDocsUrl(standard.docsUrl, 'stacks');
  return `- ${mdLink(standardTitle(standard.id), charter)}: ${registryEntry?.summary ?? standard.ownedRules.join(', ')} Full rubric: ${mdLink(`${standardTitle(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))}.`;
}).join('\n')}

## Authored Cross-Cutting Rubrics

Cross-cutting rubrics are authored standards too, but they are cataloged through item pages because they apply across many stack shapes rather than defining a deployable stack by themselves.

${crossCutting.map((standard) => `- ${mdLink(`${standardTitle(standard.id)} ${standard.latestEdition}`, normalizeStandardUrl(standard.standardUrl))}: cataloged from ${mdLink('item page', relativeDocsUrl(standard.docsUrl, 'stacks'))}.`).join('\n')}

## Published Aliases

${aliases.map((standard) => `- \`${standard.id}\`: resolves to ${mdLink(normalizeStandardUrl(standard.standardUrl), normalizeStandardUrl(standard.standardUrl))}.`).join('\n') || '- None.'}

## Planned Stack Charters

${planned.map((standard) => `- ${mdLink(standardTitle(standard.id), relativeDocsUrl(standard.docsUrl, 'stacks'))}: ${standard.ownedRules.join(', ')}.`).join('\n')}
`;
}

function generatedItemsIndex() {
  const groups = new Map();
  for (const item of compositions.stackItems) {
    if (!groups.has(item.kind)) groups.set(item.kind, []);
    groups.get(item.kind).push(item);
  }
  return [...groups.entries()].map(([kind, items]) => {
    const lines = items.map((item) => `- ${mdLink(item.title, relativeDocsUrl(item.docsUrl, 'items'))}: ${item.vcqaShouldOwn.join(', ')}.`);
    return `## ${titleize(kind)}\n\n${lines.join('\n')}`;
  }).join('\n\n');
}

function generatedCompositionsSummary() {
  const rows = compositions.composedStandards.map((standard) => {
    const docs = relativeDocsUrl(standard.docsUrl, '.');
    const full = standard.standardUrl ? mdLink(standard.latestEdition, normalizeStandardUrl(standard.standardUrl)) : 'planned';
    return `| ${docs ? mdLink(standardTitle(standard.id), docs) : standardTitle(standard.id)} | ${standard.status} | ${full} | ${standard.stackItems.map((id) => `\`${id}\``).join(', ')} |`;
  });
  return `
| Standard | Status | Edition | Composes |
|---|---|---|---|
${rows.join('\n')}
`;
}

function referenceVersionPolicy(reference) {
  if (reference.versionPolicy) return reference.versionPolicy;
  if (/\/cli\/v\d+\//.test(reference.url)) {
    const version = reference.url.match(/\/cli\/(v\d+)\//)?.[1];
    return `Pinned to ${version} upstream docs.`;
  }
  if (/\/specification\/\d{4}-\d{2}-\d{2}/.test(reference.url)) {
    const version = reference.url.match(/\/specification\/(\d{4}-\d{2}-\d{2})/)?.[1];
    return `Pinned to dated specification ${version}.`;
  }
  return 'Tracks current canonical upstream URL.';
}

function generatedReferencesPage() {
  const linkRule = references.policy?.linkHealth?.rule ?? 'Primary-source URLs are checked in CI.';
  const appliesRule = references.policy?.appliesToRule ?? '`appliesTo` uses canonical VCQA IDs; `topics` are descriptive.';
  const sourcePreference = references.policy?.sourcePreference ?? [];

  const sections = references.categories.map((category) => {
    const rows = category.references.map((reference) => {
      const appliesTo = reference.appliesTo?.length
        ? reference.appliesTo.map((id) => `\`${id}\``).join(', ')
        : '-';
      const topics = reference.topics?.length
        ? reference.topics.map((topic) => `\`${topic}\``).join(', ')
        : '-';
      const redirect = reference.expectedRedirectUrl
        ? mdLink('expected redirect', reference.expectedRedirectUrl)
        : 'none expected';
      const useFor = reference.useFor.join('; ');
      return `| ${mdLink(reference.title, reference.url)} | ${reference.publisher} | ${referenceVersionPolicy(reference)} | CI-enforced 2xx | ${redirect} | ${appliesTo} | ${topics} | ${useFor} |`;
    });

    return `## ${category.title}

${category.description}

| Reference | Publisher | Version policy | Link check | Redirect target | Controlled appliesTo | Topics | Use it for |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}`;
  }).join('\n\n');

  return `# Standards References

This is the authority map for VibeCode QA standards. These are the official specs,
framework docs, platform docs, security standards, and testing guides we cite before
writing stack-specific rubrics.

The machine-readable version lives at
[\`/standards/references.json\`](/standards/references.json). Schema:
[\`/standards/references.schema.json\`](/standards/references.schema.json).

## Registry status

- Last reviewed: **${references.lastReviewed}**
- Link health: **${references.policy?.linkHealth?.status ?? 'checked-in-ci'}**
- Link rule: ${linkRule}
- Applicability rule: ${appliesRule}

## Authoring rule

${references.policy?.authoringRule ?? 'Do not re-create broad framework doctrine when an upstream standard already exists.'}

## Source preference

${sourcePreference.map((source) => `- ${source}`).join('\n')}

${sections}
`;
}

function generatedHtmlPublishedRubrics() {
  return compositions.composedStandards
    .filter((standard) => isComposedAuthored(standard) && !isAliasOnly(standard))
    .map((standard) => {
      const registryEntry = registryById.get(standard.id);
      const edition = editionLabel(registryEntry) ?? standard.latestEdition;
      return `<tr><td>${htmlLink(standard.id, normalizeStandardUrl(standard.standardUrl), 'name')}</td><td>${escapeHtml(registryEntry?.summary ?? standard.ownedRules.join(', '))}</td><td><span class="badge live">${escapeHtml(edition)} · LIVE</span></td></tr>`;
    })
    .join('\n');
}

function generatedHtmlReferenceRepos() {
  const rows = compositions.referenceImplementations
    .filter((repo) => repo.status === 'published')
    .map((repo) => {
      const evidence = repo.reportUrl ? `${htmlLink(repo.score ? `${repo.score} report` : 'Report', repo.reportUrl)}; CI ${escapeHtml(repo.ci ?? 'unknown')}.` : 'No report yet.';
      return `<tr><td>${htmlLink(repo.id, repo.url, 'name')}</td><td>${escapeHtml(repo.demonstrates)}</td><td>${evidence}</td></tr>`;
    })
    .join('\n');
  const next = compositions.referenceImplementations
    .filter((repo) => repo.status === 'candidate')
    .map((repo) => `<code>${escapeHtml(repo.id)}</code>`)
    .join(', ');
  return `<table>
<tr><th>Repository</th><th>What it demonstrates</th><th>Score evidence</th></tr>
${rows}
</table>
<p>Next candidates: ${next}.</p>`;
}

function generatedHtmlNextStandards() {
  return plannedStandards()
    .map((standard) => {
      const label = standard.docsUrl ? htmlLink(standard.id, normalizeStandardUrl(standard.docsUrl), 'name') : `<span class="name">${escapeHtml(standard.id)}</span>`;
      return `<tr><td>${label}</td><td>${escapeHtml(standard.ownedRules.join(', '))}</td><td><span class="badge planned">planned</span></td></tr>`;
    })
    .join('\n');
}

function standardKind(standard) {
  if (isAliasOnly(standard)) return 'alias';
  if (standard.status === 'planned') return 'planned';
  if (isStackStandard(standard)) return 'authored-stack';
  return 'authored-cross-cutting';
}

function chipFor(id, optional = false) {
  const item = compositions.stackItems.find((entry) => entry.id === id);
  const standard = compositions.composedStandards.find((entry) => entry.id === id);
  const href = normalizeStandardUrl(item?.docsUrl ?? standard?.docsUrl);
  const cls = item ? 'item' : 'standard';
  const optionalClass = optional ? ' optional' : '';
  if (!href) return `<span class="chip ${cls}${optionalClass}">${escapeHtml(id)}</span>`;
  return `<a class="chip ${cls}${optionalClass}" href="${escapeHtml(href)}">${escapeHtml(id)}</a>`;
}

function markdownEntityLink(id) {
  const item = compositions.stackItems.find((entry) => entry.id === id);
  const standard = compositions.composedStandards.find((entry) => entry.id === id);
  const href = normalizeStandardUrl(item?.docsUrl ?? standard?.docsUrl ?? standard?.standardUrl);
  return href ? mdLink(id, href) : `\`${id}\``;
}

function graphModel() {
  const standards = compositions.composedStandards.map((standard) => ({
    id: standard.id,
    title: standardTitle(standard.id),
    kind: standardKind(standard),
    status: standard.status,
    docsUrl: normalizeStandardUrl(standard.docsUrl),
    standardUrl: normalizeStandardUrl(standard.standardUrl),
    latestEdition: standard.latestEdition,
    stackItems: standard.stackItems ?? [],
    optionalStackItems: standard.optionalStackItems ?? [],
    aliases: standard.aliases ?? [],
    ownedRules: standard.ownedRules ?? []
  }));
  const items = compositions.stackItems.map((item) => ({
    id: item.id,
    title: item.title,
    kind: item.kind,
    docsUrl: normalizeStandardUrl(item.docsUrl),
    references: item.references ?? []
  }));
  const referenceImplementations = compositions.referenceImplementations.map((repo) => ({
    id: repo.id,
    repo: repo.repo,
    url: repo.url,
    status: repo.status,
    standards: repo.standards ?? [],
    reportUrl: repo.reportUrl,
    score: repo.score,
    ci: repo.ci
  }));
  const edges = [
    ...standards.flatMap((standard) => [
      ...standard.stackItems.map((item) => ({ from: item, to: standard.id, type: 'composes' })),
      ...standard.optionalStackItems.map((item) => ({ from: item, to: standard.id, type: 'optional' }))
    ]),
    ...referenceImplementations.flatMap((repo) => (repo.standards ?? []).map((standard) => ({
      from: repo.id,
      to: standard,
      type: 'demonstrates'
    }))),
    ...standards.filter((standard) => standard.kind === 'alias').map((standard) => ({
      from: standard.id,
      to: standard.standardUrl,
      type: 'aliases'
    }))
  ];
  return { version: 1, source: 'standards/compositions.json', standards, items, referenceImplementations, edges };
}

function generatedGraphContent() {
  const model = graphModel();
  const groups = [
    ['Authored Stack Rubrics', model.standards.filter((standard) => standard.kind === 'authored-stack'), 'authored'],
    ['Authored Cross-Cutting Rubrics', model.standards.filter((standard) => standard.kind === 'authored-cross-cutting'), 'crosscut'],
    ['Published Aliases', model.standards.filter((standard) => standard.kind === 'alias'), 'authored'],
    ['Planned Standards', model.standards.filter((standard) => standard.kind === 'planned'), 'planned']
  ];
  const standardCards = groups.map(([heading, standards, cls]) => `
<h2 id="${heading.toLowerCase().replaceAll(' ', '-')}">${heading}</h2>

<div class="standard-grid">
${standards.map((standard) => {
  const links = [
    standard.docsUrl ? htmlLink('catalog', standard.docsUrl) : null,
    standard.standardUrl ? htmlLink('rubric', standard.standardUrl) : null
  ].filter(Boolean).join('');
  const chips = [
    ...(standard.stackItems ?? []).map((id) => chipFor(id)),
    ...(standard.optionalStackItems ?? []).map((id) => chipFor(id, true))
  ].join('\n      ');
  const summary = registryById.get(standard.id)?.summary ?? standard.ownedRules.join(', ');
  const edition = standard.latestEdition ? ` ${standard.latestEdition}` : '';
  return `  <div class="standard-card ${cls}">
    <div class="title"><strong>${standard.docsUrl ? htmlLink(standard.id, standard.docsUrl) : escapeHtml(standard.id)}</strong><span class="status">${escapeHtml(standard.status)}${escapeHtml(edition)}</span></div>
    <div class="kind">${escapeHtml(summary)}</div>
    <div class="chips">
      ${chips || '<span class="chip">metadata-only</span>'}
    </div>
    <div class="links">${links}</div>
  </div>`;
}).join('\n')}
</div>`).join('\n\n');

  const templates = model.referenceImplementations.map((repo) => {
    const evidence = [repo.reportUrl ? htmlLink(repo.score ? `${repo.score} report` : 'report', repo.reportUrl) : null, repo.ci ? `CI ${escapeHtml(repo.ci)}` : null].filter(Boolean).join(' · ');
    return `  <div class="node template">
    <div class="title"><strong>${htmlLink(repo.id, repo.url)}</strong><span class="status">${escapeHtml(repo.status)}</span></div>
    <div class="chips">${repo.standards.map((id) => chipFor(id)).join('')}</div>
    <div class="links">${evidence}</div>
  </div>`;
  }).join('\n');

  const itemGroups = new Map();
  for (const item of model.items) {
    if (!itemGroups.has(item.kind)) itemGroups.set(item.kind, []);
    itemGroups.get(item.kind).push(item);
  }
  const items = [...itemGroups.entries()].map(([kind, group]) => {
    const chips = group.map((item) => item.docsUrl ? `<a class="chip item" href="${escapeHtml(item.docsUrl)}">${escapeHtml(item.id)}</a>` : `<span class="chip item">${escapeHtml(item.id)}</span>`).join('');
    return `  <div class="item-card"><strong>${escapeHtml(titleize(kind))}</strong><div class="chips">${chips}</div></div>`;
  }).join('\n');

  return `
<div class="legend">
  <div class="node authored"><strong>Authored stack rubric</strong><br><span class="kind">Deployable stack standard with stable rule IDs.</span></div>
  <div class="node crosscut"><strong>Authored cross-cutting rubric</strong><br><span class="kind">First-class rubric applied across stack shapes.</span></div>
  <div class="node planned"><strong>Planned standard</strong><br><span class="kind">Cataloged rule surface; full rubric is not published yet.</span></div>
  <div class="node item"><strong>Stack item leaf</strong><br><span class="kind">Framework, runtime, tool, protocol, quality, or supply-chain layer.</span></div>
  <div class="node template"><strong>Reference template</strong><br><span class="kind">Runnable repo with CI and a tracked VCQA report.</span></div>
</div>

<p class="kind">Generated graph data: <a href="/standards/graph.json"><code>graph.json</code></a>.</p>

<h2 id="reference-templates">Reference Templates</h2>

<div class="template-row">
${templates}
</div>

${standardCards}

<h2 id="stack-item-leaves">Stack Item Leaves</h2>

<div class="item-grid">
${items}
</div>
`;
}

function standardsUsing(id, selfId) {
  return compositions.composedStandards
    .filter((standard) => standard.id !== selfId)
    .filter((standard) => (standard.stackItems ?? []).includes(id) || (standard.optionalStackItems ?? []).includes(id));
}

function relatedStandardsFor(standard) {
  const direct = new Map();
  for (const item of [...(standard.stackItems ?? []), ...(standard.optionalStackItems ?? [])]) {
    for (const related of standardsUsing(item, standard.id)) {
      if (!isAliasOnly(related)) direct.set(related.id, related);
    }
  }
  for (const id of registryById.get(standard.id)?.recommends ?? []) {
    const related = compositions.composedStandards.find((entry) => entry.id === id);
    if (related && !isAliasOnly(related)) direct.set(related.id, related);
  }
  return [...direct.values()].slice(0, 8);
}

function generatedRelatedSection(standard) {
  const registryEntry = registryById.get(standard.id);
  const latest = registryEntry?.editions?.find((edition) => edition.status === 'latest');
  const templates = compositions.referenceImplementations.filter((repo) => (repo.standards ?? []).includes(standard.id));
  const related = relatedStandardsFor(standard);
  const composed = [
    ...(standard.stackItems ?? []).map((id) => markdownEntityLink(id)),
    ...(standard.optionalStackItems ?? []).map((id) => `${markdownEntityLink(id)} (optional)`)
  ].join(', ');
  const lifecycle = latest?.lifecycle;
  const lifecycleText = lifecycle
    ? `Edition lifecycle: ${lifecycle.deprecated ? 'deprecated' : 'active'}${lifecycle.supersededBy ? `, superseded by ${lifecycle.supersededBy}` : ''}. Errata: ${lifecycle.errata.length ? lifecycle.errata.join('; ') : 'none'}.`
    : 'Edition lifecycle metadata is unavailable.';

  return `
## Related Standards

Reports and scans should cite this pinned edition URL:
<${registryEntry?.standardUrl ?? standard.standardUrl}>

- Catalog page: ${standard.docsUrl ? mdLink(standard.docsUrl, normalizeStandardUrl(standard.docsUrl)) : 'none'}
- Latest edition: \`${standard.latestEdition}\`
- ${lifecycleText}
- Composes: ${composed || 'metadata-only'}
- Reference implementations: ${templates.length ? templates.map((repo) => mdLink(repo.id, repo.url)).join(', ') : 'none yet'}
- Related standards: ${related.length ? related.map((entry) => entry.standardUrl ? mdLink(entry.id, normalizeStandardUrl(entry.standardUrl)) : (entry.docsUrl ? mdLink(entry.id, normalizeStandardUrl(entry.docsUrl)) : `\`${entry.id}\``)).join(', ') : 'none'}
`;
}

const changed = [
  writeJsonIfChanged('standards/graph.json', graphModel()),
  replaceGeneratedBlock('docs/docs/standards/index.md', 'standards-inventory', generatedStandardsCatalog()),
  replaceGeneratedBlock('docs/docs/standards/index.md', 'reference-implementations', generatedReferenceRepos()),
  replaceGeneratedBlock('docs/docs/standards/stacks/index.md', 'stack-standards-inventory', generatedStackIndex()),
  replaceGeneratedBlock('docs/docs/standards/items/index.md', 'stack-items-inventory', generatedItemsIndex()),
  replaceGeneratedBlock('docs/docs/standards/compositions.md', 'composition-summary', generatedCompositionsSummary()),
  replaceGeneratedBlock('docs/docs/standards/graph.md', 'standards-graph', generatedGraphContent()),
  replaceGeneratedBlock('docs/docs/stacks.md', 'authored-rubrics', generatedStacksPageRubrics()),
  writeIfChanged('docs/docs/standards/references.md', generatedReferencesPage()),
  replaceGeneratedTomlBlock('docs/zensical.toml', 'nav-stack-standards', generatedNavStackStandards(), '      '),
  replaceGeneratedTomlBlock('docs/zensical.toml', 'nav-stack-items', generatedNavStackItems(), '      '),
  replaceGeneratedTomlBlock('docs/zensical.toml', 'nav-assessments', generatedNavAssessments(), '      '),
  replaceGeneratedBlock('standards/index.html', 'published-rubrics', generatedHtmlPublishedRubrics()),
  replaceGeneratedBlock('standards/index.html', 'reference-implementations', generatedHtmlReferenceRepos()),
  replaceGeneratedBlock('standards/index.html', 'next-standards', generatedHtmlNextStandards()),
  ...compositions.composedStandards
    .filter((standard) => isComposedAuthored(standard) && !isAliasOnly(standard))
    .map((standard) => replaceGeneratedBlock(`standards/${standard.id}/docs/v1/index.md`, 'related-standards', generatedRelatedSection(standard)))
].filter(Boolean);

if (checkOnly && changed.length) {
  process.exit(1);
}

if (!checkOnly) {
  console.log(changed.length ? `Updated ${changed.length} generated catalog block(s)` : 'Generated catalog blocks are current');
}
